### ISSUE TITLE
Feature request: read go.mod not located in current directory

### ISSUE THREAD

**Issue by torkelrogstad** [dustinblackman/gomodrun#1]
Adding tools to my `go.mod` file screws with other declared dependencies. It'd be nice if `gomodrun` could take a parameter that specifies where to look for the tools file and `go.mod`, so I could keep my actual dependencies distinct from tooling dependencies

**Comment by dustinblackman** [comment]
Interesting! What would your directory setup look like in your use case? There may be a nice way to avoid having to pass two parameters, and instead just one to point to the specified `go.mod`.

**Comment by torkelrogstad** [comment]
I have all my go packages as root level directories. So I was thinking something like this: 
```
- package1
- package2
- tools
-- go.mod
-- go.sum
-- tools.go
```

Could then do something like `gomodrun --mod tools go-tool-to-execute` or `gomodrun --mod tools/mod.go go-tool-to-execute`. `gomodrun` could then look for a tools file in the same directory as the given `go.mod` file. 

What do you think about that?

**Comment by dustinblackman** [comment]
First option looks good! I'll see about finding time on the weekend to add it.

**Comment by torkelrogstad** [comment]
Great! Ping me if you want help with testing :smile:

**Comment by dustinblackman** [comment]
Solved in https://github.com/dustinblackman/gomodrun/commit/2890f1baa58d00f1ec56a8e2831b8d1c75823472
