### ISSUE TITLE
brew isntall Error 

### ISSUE THREAD

**Issue by kawaiiyoshiyuki** [dustinblackman/gomodrun#3]
Hi I tried to install gomodrun with brew on MacBook Pro with Os Monterey but received these errors:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/18661223/168806162-b6bfdae7-0b1a-47fd-a195-010cb0630de6.png">
Thanks for any help, let me know if I can assist.

**Comment by dustinblackman** [comment]
Sorry I had missed this notification. It's been fixed!
